# dnsmasq.conf — DHCP + DNS hijack para portal cautivo
interface=wlx98038e5c6843
bind-interfaces

# DHCP: asigna IPs a clientes que se conecten al AP
dhcp-range=10.0.0.10,10.0.0.50,12h
dhcp-option=3,10.0.0.1        # gateway
dhcp-option=6,10.0.0.1        # DNS apunta al propio AP

# DNS hijack: todo dominio resuelve a nuestra IP (portal)
address=/#/10.0.0.1

# Log para el laboratorio
log-queries
log-facility=/home/debian/captive_portal/logs/dnsmasq.log
