# hostapd.conf — Rogue AP para laboratorio
interface=wlx98038e5c6843
driver=nl80211
ssid=FreeWiFi_Lab
hw_mode=g
channel=6
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
# Sin cifrado — AP abierto para capturar tráfico de prueba
wpa=0
